### ISSUE TITLE
[Rust] Feature tracking

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#2703]
### Feature tracking issue for `Rust` language support:

- [x] Rust AST
- [x] Rust AST Printer
- [ ] `Fable2Rust`:

    - [x] modules
    - [x] primitives
        - [x] bool
        - [x] char
        - [x] string
        - [x] integers
        - [x] floats
    - [x] control flow
    - [x] functions
    - [x] lambdas
    - [x] records
    - [x] unions
    - [x] arrays
    - [x] lists
    - [x] tuples
    - [x] options
    - [x] sequences
    - [x] enums (some)
    - [x] classes (some)
    - [x] interfaces (most)
    - [x] imports (some)
    - [x] comparers (some)
    - [ ] conversions
    - [ ] formatting
    - [ ] exceptions
    - [ ] reflection
    - [ ] async
    - [ ] threading

- [ ] `fable-library-rust`
    - [x] Array (most)
    - [x] ResizeArray (most)
    - [x] List (most)
    - [x] Seq (most)
    - [x] Option (most)
    - [x] Range
    - [ ] Choice
    - [ ] Result
    - [ ] Map
    - [ ] Set
    - [ ] Dictionary
    - [ ] HashSet
    - [ ] Decimal
    - [ ] BigInt
    - [ ] Guid
    - [ ] DateTime
    - [ ] DateTimeOffset
    - [ ] Timer
    - [ ] String
    - [ ] Unicode
    - [ ] RegExp
    - [ ] Event
    - [ ] Observable
    - [ ] other FSharp.Core modules
    - [ ] other .NET BCL implementations

**Comment by alfonsogarciacaro** [comment]
This is great @ncave, thank you! It's very nice to be able to easily the current status of Rus compilation. I just created one of this new Github projects for Beyond. If you want you can use it to track the progress or we can just link to this issue from there: https://github.com/orgs/fable-compiler/projects/6/views/1

**Comment by delneg** [comment]
> This is great @ncave, thank you! It's very nice to be able to easily the current status of Rus compilation. I just created one of this new Github projects for Beyond. If you want you can use it to track the progress or we can just link to this issue from there: https://github.com/orgs/fable-compiler/projects/6/views/1

Sorry to interrupt, but the link above seems to be broken (or private ? not sure how it works)

**Comment by alfonsogarciacaro** [comment]
Thanks for letting me know @delneg! Seems the project had private visibility by default, I've changed it. Can you please try again?

**Comment by delneg** [comment]
<img width="899" alt="Screenshot 2022-01-10 at 12 55 03" src="https://user-images.githubusercontent.com/10036256/148746920-feb8ebd1-6e4f-45dc-b45d-c23b15712294.png">
Yes now it seems to work

**Comment by alexswan10k** [comment]
Hey @ncave, I was reading around and found [this discussion on dyn* sizing](https://smallcultfollowing.com/babysteps/blog/2022/03/29/dyn-can-we-make-dyn-sized/) the other day. I know we currently have a solution for interfaces (wrapping in ```Rc<dyn IThing>```), but on the surface it appears this might help substantially simplify the approach. Seems like early days yet but one to keep an eye on anyway.

**Comment by alexswan10k** [comment]
I feel like this is getting close to being able to actually use it. I have been thinking about perhaps using this for a smallish toy project (specifically a wasm target). Perhaps even a game or something with bevy, where the interop layer will all be in Rust, but all high level logic in F#.

I noticed that crates.io does not yet have fable-core reserved. What steps realistically need to be done to set up publishing? Are we even close to considering this? Perhaps I can look at using git in the meantime.

**Comment by ncave** [comment]
@alexswan10k
`Fable.Core` doesn't actually contain any code, just metadata, so no need to publish that as a crate.

For `fable-library-rust`, even though for now it's copied directly to the output folder by the `fable` tool, we probably do want to reserve the crate name.

**Comment by alexswan10k** [comment]
Oh, that is kind of a nice way of doing it too, although perhaps not the first thing a Rust user would expect. I will experiment with this for now, cheers. Is there some kind of example? I believe your raytracer example was using local relative paths to core fable repo.

**Comment by ncave** [comment]
@alexswan10k Any project you compile with `fable` gets the `fable-library-*` local package copied in the `outDir/fable_modules` folder. `Fable.Core` is something else, it's just a metadata assembly (published on Nuget) that you reference in your F# project.

**Comment by alexswan10k** [comment]
Sorry probably just me using the incorrect name. 

Just tested, this works great. Thanks. I will have a play with this.

**Comment by alexswan10k** [comment]
@ncave another conundrum.

```
[<Struct>]
type Vector2<[<Measure>] 'a> = {
    x: float32<'a>
    y: float32<'a>
} 
with
    static member (+) (v1 : Vector2<'a>, v2: Vector2<'a>) =
        { x = v1.x + v2.x; y =  v1.y + v2.y }
    static member (-) (v1 : Vector2<'a>, v2: Vector2<'a>) =
        { x = v1.x - v2.x; y =  v1.y - v2.y }
    static member (+) (v : Vector2<'a>, s) =
        { x = s + v.x; y =  s + v.y }
```

This spits out generic parameters for ```[<Measure>]``` leading to all sorts of interesting problems

```
    pub struct Vector2<a: Clone + 'static> {
        pub x: f32,
        pub y: f32,
    }
    impl <a: Clone + 'static> Entities::Vector2<a> {
        pub fn op_Addition__1A4083A0(v1: Entities::Vector2<a>,
                                     v2: Entities::Vector2<a>)
         -> Entities::Vector2<_> {
            Entities::Vector2::<_>{x: v1.x + v2.x, y: v1.y + v2.y,}
        }
        pub fn op_Subtract
```

What would be best to fix this? It seems plausible to just erase ```[<Measure>]``` generics, but I am not confident that will not lead to other problems.

Happy to write up some tests etc for this scenario shortly.


On a random F# tangent, I don't suppose anyone knows how to best express this sort of thing correctly with generalization?
```
    let square//<[<Measure>] 'a> 
        (f: float32<'a>): float32<'a^2> =
        (Math.Pow(f |> float, 2) |> float32) * 1f<_>
```

It seems the second I kick in the generic constraint, I cannot cast to ```<_>``` or ```<'a^2>``` etc

**Comment by ncave** [comment]
@alexswan10k I haven't used generic units of measure much, do you want to open a separate issue for discussion?
We can keep this one just for Rust feature tracking and related topics.

**Comment by alfonsogarciacaro** [comment]
@alexswan10k GenericParams include now a `isMeasure` field. In that for example we use it to discard measure parameters: https://github.com/fable-compiler/Fable/blob/ea973444f30662deddf8c85053f76fc9baf6db7e/src/Fable.Transforms/Dart/Fable2Dart.fs#L488-L491

**Comment by joprice** [comment]
@gmono  I'm not a maintainer, but if you check the commit history, the majority of activity over the last few months has been on the rust target. Seems it's getting some love. I'm excited to take it for a spin soon.

**Comment by MangelMaxime** [comment]
Hello,

Yes currently the actively developed target are:

- JavaScript (stable)
- TypeScript (stable as it is using the JavaScript under the hood, there are still some type info that we can get wrong but we fix then when reported)
- Python (beta), I know some people already use it in production
- Rust (beta)

**Comment by ShalokShalom** [comment]
Is there an overview on how Rusts borrow checker is utilized?

As far as I know, does the Rust backend simply utilize the Fable types to implement memory management.

And since Rust has lifetimes and ownership semantics encoded in the type signature, I assume this is how it works?

My question would be the expected performance characteristics?

I assume it would be around the GC level of .NET, yes?

Since assuming it would be native Rust performance would be just wishful thinking, I guess? 😉 

Thanks a lot

**Comment by ncave** [comment]
@ShalokShalom Most borrow checker issues are currently handled through cheap cloning. Memory management is mainly RC smart pointers and RAII. Performance is close to managed .NET (which nowadays is pretty fast and competitive with native code). But yes, there are more perf optimizations that can be done, for example byref calling convention, etc.
