### ISSUE TITLE
Complete the new build system

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3536]
### Description

This issue is a follow up of the work done in #3529 

## Old build system overview

While trying to work on Fable, I discovered that the `build.fsx` was having several issues:

- No code unification between the different targets
-  Build process was difficult to understand because it was not always easy to understands what the code was doing
	- Extensive usage of callbacks
	- `List.fold`
- Not everything was defined inside of the `build.fsx`, but was also using some function from `Fable.PublishUtils` which is kind of fine but also using `npm scripts` making it difficult to follow the order of execution

## New build system goals

- Have everything define in a single place/project
- Have a more declarative code making it easier to follow what each step does and minimise usage of `callbacks`
- Make it easy to share codes when possible or re-use code
	- Good exemple of that is the `BuildFableLibrary` which allows each target to provide a few parameters but encapsulate all the logic possible
	- Ability to re-use others command handler like `github-release` which re-use `publish` handler
- Setup a VSCode devcontainer making it easier for anyone to contribute to Fable and also workaround the current limitation of not being able to compile the **Fable standalone** on OXS (seems to be a dotnet runtime edge case...)
- Clean VSCode tasks and launch configuration that are not usable anymore + add new ones for things that can be supported and improve the developer experience

In the future, I will move some of the helpers function like changelog parsing, fsproj/package.json manipulation into a library. To simply the project and make it usable for others projects too.

## Tasks

However, for all the good things that the new build system provide there are still things that needs to be completed:

- [x] Update `PackageReleaseNotes` node in the fsproj when releasing new version.

	https://github.com/fable-compiler/Fable/commit/d60e3a922dcc831c5564d2e3cae6202ecdfcfdf2#r130824463

- [x] Port and fix the `fable-standalone` command https://github.com/fable-compiler/Fable/blob/main/build.fsx#L860-L862

	Currently, terser seems to be running without ever completing (let it run for more than 30min without success).
	
	Investigate if we can use `vite` instead of rollup/terser. I tested using `esbuild` and it was able to bundle the project in less than a second. But I need more time to complete the work on:

- [x] Port the `fable-compiler-js` command https://github.com/fable-compiler/Fable/blob/main/build.fsx#L857-L859
	
	Waiting for `fable-standalone`

- [x] Port the `fable-worker` command https://github.com/fable-compiler/Fable/blob/main/build.fsx#L863-L865

		Waiting for `fable-standalone`

- [ ] Fix sync with Ncava FCS repo (see https://github.com/fable-compiler/Fable/issues/3531)
- [x] Port the `package` command https://github.com/fable-compiler/Fable/blob/main/build.fsx#L842-L844
- [x] Port the `package-core` command https://github.com/fable-compiler/Fable/blob/main/build.fsx#L845-L847
- [x] Activate support for publishing `fable-standalone`

	Waiting for `fable-standalone`

- [x] Activate support for publishing `fable-compiler-js`

	Waiting for `fable-standalone`
