### ISSUE TITLE
Roadmap help requested

### ISSUE THREAD

**Issue by mike-morr** [fable-compiler/Fable#936]
These are my opinions for the roadmap, definitely looking for edits, additions, deletes.  I would have added this as a wiki page, but I need permissions from @alfonsogarciacaro or someone else.  I would just give rights to the @fable-compiler/community, @fable-compiler/code-maintenance, and @fable-compiler/documentation  teams.

**EDIT:** Just to be clear, I would love to see contributions to the roadmap from both team members and consumers of Fable.

### 1.0 Beta 2
- [ ] Stabilize and Finalize types for Node, JS, and Browser
- [x] Separate Browser and Node types from Fable.Core
- [ ] Make output of dotnet fable display help when not enough params specified.  [Tracked here](https://github.com/fable-compiler/Fable/issues/926)
- [ ] Add missing types to Node types
- [x] Update all samples to 1.0 beta 2 with Paket.  [Tracked here](https://github.com/fable-compiler/Fable/issues/881)
- [x] Compile Fable to JS without bundling [see PR](https://github.com/fable-compiler/Fable/pull/935)

### 1.0 Beta 3
- [ ] Bug fixes
- [ ] Initial Build Performance Improvements 
- [ ] Ts2Fable Improvements
- [ ] Update Documentation

### 1.0 Final
- [ ] All the above

### 1.1
- [ ] Separate elmish into it's own CLI with ability to add routes and new controls via CLI

**Comment by alfonsogarciacaro** [comment]
@mizzle-mo This is very nice, thank you! I personally I don't like the wiki to keep track of progress, have you seen the new Projects feature of Github? I haven't used it yet but it seems it allows you to convert issues into something like Trello cards to better visualize progress of milestones ([example]/https://github.com/dotnet/cli/projects/3)), similar to what people have been doing so far with labels. Maybe it's a good fit for something like this?

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro I think projects would indeed be a better fit.  If you want to grant permissions, I can get started on putting it together.

**Comment by mizzle-mo** [comment]
Added inital build speed to 1.0 Beta 3, I would be ok with moving this to final as a minor release as well.  I think we need to get to the point where we can ship it!  🚢 :shipit:

**Comment by MangelMaxime** [comment]
For **1.0 Beta 2** we should also planned to allow Fable to be used in standalone mode (withouth webpack) [see](https://github.com/fable-compiler/Fable/issues/800#issuecomment-302883751)

**Comment by mizzle-mo** [comment]
@MangelMaxime Thanks! Added to Beta 2 as requested.

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro https://github.com/orgs/fable-compiler/projects?query=is%3Aopen+sort%3Aupdated-asc Took an initial stab at creating the projects.

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro @MangelMaxime I put the project under the organization since it allows you to add cards from any repo in the org, which I thought made the most sense given the current structure.  So we could tag fable-electron, fable-elmish, and ts2fable issues and PRs in any project.

**Comment by alfonsogarciacaro** [comment]
Closing for now as Fable 1.2 has been released, we can reopen or create a new issue for Fable 1.3 or 2.0... but please let's do it after FableConf and taking a break :wink:
